
import { GoogleGenAI, Type } from "@google/genai";
import type { DetectionResult } from '../types';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const model = 'gemini-2.5-pro';

const detectionSchema = {
  type: Type.OBJECT,
  properties: {
    isAiGenerated: {
      type: Type.BOOLEAN,
      description: "True if the image is likely AI-generated, false otherwise.",
    },
    confidence: {
      type: Type.NUMBER,
      description: "A value from 0.0 (certainly human) to 1.0 (certainly AI).",
    },
    analysis: {
      type: Type.STRING,
      description: "A brief, one-paragraph summary of the findings and key indicators.",
    },
    modelGuessed: {
      type: Type.STRING,
      description: "The best guess for the AI model used (e.g., Midjourney, DALL-E 3), or 'N/A' if unknown or human-made.",
    },
    suspiciousRegions: {
      type: Type.ARRAY,
      description: "A list of regions in the image that show signs of AI generation.",
      items: {
        type: Type.OBJECT,
        properties: {
          area: {
            type: Type.STRING,
            description: "A description of the location of the suspicious area (e.g., 'the subject's left hand', 'background details on the right')."
          },
          reason: {
            type: Type.STRING,
            description: "A brief explanation of why this area is suspicious (e.g., 'unnatural finger structure', 'garbled text', 'inconsistent lighting')."
          },
        },
        required: ["area", "reason"],
      },
    },
  },
  required: ["isAiGenerated", "confidence", "analysis", "modelGuessed", "suspiciousRegions"],
};


export async function detectImage(imageBase64: string, mimeType: string): Promise<DetectionResult> {
  const prompt = `Analyze the provided image to determine if it was generated by an AI model. Scrutinize the image for common AI artifacts, such as unnatural textures, inconsistencies in lighting and shadows, distorted or extra limbs/fingers, garbled text, and perfectly symmetrical but illogical patterns. Based on your analysis, provide a detailed response in JSON format. The JSON object must conform to the specified schema.`;

  const imagePart = {
    inlineData: {
      data: imageBase64,
      mimeType: mimeType,
    },
  };

  const textPart = {
    text: prompt
  };

  try {
    const response = await ai.models.generateContent({
        model: model,
        contents: { parts: [imagePart, textPart] },
        config: {
          responseMimeType: "application/json",
          responseSchema: detectionSchema,
        },
    });

    const jsonString = response.text;
    const result = JSON.parse(jsonString);

    // Basic validation to ensure the result matches the expected structure
    if (typeof result.isAiGenerated !== 'boolean' || typeof result.confidence !== 'number') {
        throw new Error("API returned an invalid JSON structure.");
    }
    
    return result as DetectionResult;

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to get a valid response from the AI model.");
  }
}
